server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: product-db


logging:
  level:
    root: INFO
    com.smithjilks.microservices: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080