server.port: 7003
server.error.include-message: always

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/review-db
    username: postgres
    password: postgres
    hikari.initializationFailTimeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # this recreates the db, not recommended for prod. Strongly recommend to set this property to "none" in a production environment!
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: INFO
    com.smithjilks.microservices: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080